### PR TITLE
fix(img_link)

### PR DESCRIPTION
**Pull request by kaldan007**
updated img link with iiif-dev

### CODE REVIEW

**Review by eroux — COMMENTED** [review]
why did you do this change? I think it's best to keep iiif instead of iiif-dev

**Comment by kaldan007** [comment]
I changed this as iiif one is not working on our editor. when i check with img link obtained from bdrc, i noticed the different and hence the change.

**Comment by eroux** [comment]
ah I see what's happening... It should work now if you log out and log in again from BDRC if you use iiif. Please report that kind of issues instead of implementing workarounds

**Comment by kaldan007** [comment]
Sure @eroux, I will roll back the changes. I will keep that in mind.

**Pull request merged**
